DROP TABLE IF EXISTS flights CASCADE;

CREATE TABLE flights (
  id SERIAL PRIMARY KEY NOT NULL,
  IATA VARCHAR(255),
  AIRLINE_ID VARCHAR(255),
  START_AIRPORT VARCHAR(255),
  START_AIRPORT_ID VARCHAR(255),
  DESTINATION_AIRPORT VARCHAR(255),
  DESTINATION_AIRPORT_ID VARCHAR(255),
  CODE_SHARE VARCHAR(255),
  STOPS VARCHAR(255),
  EQUIPMENT VARCHAR(255)
)